# Generated by Django 3.2.12 on 2022-03-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20220313_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genres',
            new_name='end',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='start',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
