# Generated by Django 3.2.12 on 2022-03-14 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_book_simple_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='simple_title',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage', models.TextField()),
                ('usable', models.BooleanField()),
                ('unusability_desc', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.book')),
            ],
        ),
    ]
