# Generated by Django 3.2.12 on 2022-03-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20220314_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='difficulty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='passage_num',
            field=models.IntegerField(null=True),
        ),
    ]
