# Generated by Django 3.2.12 on 2022-03-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20220315_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='passages',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
