# Generated by Django 3.2.12 on 2022-03-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20220315_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='difficulty',
            field=models.IntegerField(blank=True),
        ),
    ]
