# Generated by Django 3.2.12 on 2022-03-16 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20220315_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='active',
        ),
    ]
