# Generated by Django 3.2.12 on 2022-03-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20220316_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passage',
            name='book',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Passage',
        ),
    ]
