# Generated by Django 3.2.12 on 2022-03-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='points_required',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='avatar',
            field=models.ImageField(null=True, upload_to='rewards/'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
